// <auto-generated />
namespace Resturant_os.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFoodsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFoodsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003102312124_addFoodsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
